# action.yml
name: 'S3cmd Docker Action'
author: 'Sajad Safarveisi'
description: 'Use s3cmd to interact with an S3-compatible service.'
inputs:
  command:  
    description: 'command to be executed by s3cmd (e.g., "put file.txt s3://my-bucket")'
    required: true
  access-key:
    description: 'Access key id'
    required: true
  secret-key:
    description: 'Secret access key'
    required: true
  endpoint-url:
    description: 'Endpoint url for the s3 service (e.g., s3-de-central.profitbricks.com)'
    required: true
  bucket-location:
    description: 'Region where your s3 bucket is located (e.g., EU)'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.access-key }}
    - ${{ inputs.secret-key }}
    - ${{ inputs.endpoint-url }}
    - ${{ inputs.bucket-location }}