#!/bin/bash

##############################################################
## Starts a local mlflow server with s3 artifactory storage ##
##############################################################

mlflow server \
    --backend-store-uri sqlite:///ml_platform.db \
    --artifacts-destination s3://customerintelligence/ml_platform/mlartifacts \
    --host 0.0.0.0 --port 5000 \