channels:
- conda-forge
dependencies:
- python=3.9.1
- pip<=24.0
- pip:
  - mlflow==2.20.0
  - xgboost==2.1.3
  - scikit-learn==1.5.2
  - mlserver==1.6.1
  - mlserver-mlflow==1.6.1
  - pydantic==2.7.1
  - conda-pack==0.8.1
name: mlflow-env
