#!/bin/bash

accessKey=$1
secretKey=$2
s3EndPoint=$3
bucketLocation=$4

sed -i s/{{AWS_ACCESS_KEY_ID}}/${accessKey}/g .s3cfg
sed -i s\|{{AWS_SECRET_ACCESS_KEY}}\|${secretKey}\|g .s3cfg
sed -i s/{{S3_ENDPOINT_URL}}/${s3EndPoint}/g .s3cfg
sed -i s/{{BUCKET_LOCATION}}/${bucketLocation}/g .s3cfg