apiVersion: spark.stackable.tech/v1alpha1
kind: SparkApplication
metadata:
  name: pyspark-ml-platform
  namespace: default
spec:
  sparkImage:
    custom: ciaa/data_platform_spark:added-require
    productVersion: 3.5.2
    pullPolicy: Always
  mode: cluster
  mainApplicationFile: local:///stackable/ml_platform/script.py
  sparkConf:
    spark.hadoop.fs.s3a.aws.credentials.provider: "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    spark.hadoop.fs.s3a.path.style.access: "true"
    spark.hadoop.fs.s3a.access.key: "${CUSTOM_S3_ACCESS_KEY}"
    spark.hadoop.fs.s3a.secret.key: "${CUSTOM_S3_SECRET_KEY}"
    spark.hadoop.fs.s3a.endpoint: "${CUSTOM_S3_ENDPOINT}"
    spark.hadoop.fs.s3a.connection.ssl.enabled: "false"
    spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    spark.hadoop.fs.s3a.endpoint.region: "${CUSTOM_S3_ENDPOINT_REGION}"
  volumes:
    - name: job-python-script
      configMap:
        name: job-python-script
  driver:
    config:
      resources:
        cpu:
          min: "1"
          max: "2"
        memory:
          limit: "1Gi"
      volumeMounts:
        - name: job-python-script
          mountPath: stackable/ml_platform
  executor:
    replicas: 2
    config:
      resources:
        cpu:
          min: "1"
          max: "2"
        memory:
          limit: "2Gi"
      volumeMounts:
        - name: job-python-script
          mountPath: stackable/ml_platform