name: Update Mlflow Artifact Path and Deploy Champion Model on Kserve

on:
  push:
    branches:
      - master # Trigger the workflow every time there is a push to the master branch
    tags:
      - "[0-9]*.[0-9]*.[0-9]*" # Trigger the workflow every time there is a new tag
    paths:
      - "ml_platform/best_model_artifacts/.env.best_run" # When new best model run id is available

env:
  best_model_directory: ml_platform/best_model_artifacts
  inference_directory: inference_service

jobs:

  mlflow-environment-artifact:
    runs-on: ubuntu-24.04
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
      
      - name: Load .env file and add new env variables to the job
        uses: xom9ikk/dotenv@v2.3.0
        with:
          path: ./${{ env.best_model_directory }}
          mode: best_run
          load-mode: strict
      
      - name: Get conda.yaml from the best MLflow run's artifactory path on S3
        uses: ./.github/actions/s3cmd-docker  
        with:
          command: get s3://customerintelligence/${{ env.MLFLOW_ARTIFACTORY_PREFIX }}/${{ env.ARTIFACTS_PATH }}/conda.yaml
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          host_base: ${{ secrets.S3_ENDPOINT_URL }}
          bucket_location: ${{ secrets.BUCKET_LOCATION }}

      - name: Set up miniconda and activate conda virtual env
        uses: conda-incubator/setup-miniconda@v3
        with: 
          auto-activate-base: false
          channels: conda-forge,defaults
          environment-file: ./conda.yaml
          activate-environment: mlflow-env # Name of the virtual env in the conda.yaml

      - name: Make a Tarball of the Environment
        shell: bash -l {0}
        run: |
          conda-pack -o environment.tar.gz -f

      - name: Upload environment.tar.gz to the best MLflow run's artifactory path on S3
        uses: ./.github/actions/s3cmd-docker  
        with:
          command: put environment.tar.gz s3://customerintelligence/${{ env.MLFLOW_ARTIFACTORY_PREFIX }}/${{ env.ARTIFACTS_PATH }}/environment.tar.gz
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          host_base: ${{ secrets.S3_ENDPOINT_URL }}
          bucket_location: ${{ secrets.BUCKET_LOCATION }}

  deploy-to-kserve:
      if: ${{ startsWith(github.ref, 'refs/tags/') }} # Skip this job if there isn't any new tag pushed
      needs: [mlflow-environment-artifact]
      runs-on: ubuntu-24.04
      steps:
        - name: Check Out Code
          uses: actions/checkout@v4

        - name: Set up Kubectl
          uses: azure/setup-kubectl@v4
        
        - name: Set K8s context
          uses: Azure/k8s-set-context@v4
          with:
            kubeconfig: ${{ secrets.KUBECONFIG }}
        
        - name: Load .env file and add new env variables to the job
          uses: xom9ikk/dotenv@v2.3.0
          with:
              path: ./${{ env.best_model_directory}}
              mode: best_run
              load-mode: strict

        - name: Deploy the Mlflow champion model to Kserve
          working-directory: ${{ env.inference_directory}}
          env:
            S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            S3_REGION: ${{ secrets.S3_REGION }}
            ARTIFACTS_PATH: ${{ env.ARTIFACTS_PATH }}
            MLFLOW_ARTIFACTORY_PREFIX: ${{ env.MLFLOW_ARTIFACTORY_PREFIX }}
          run: |
            envsubst < mlflow.yml | kubectl apply -f -