name: Update Artifact Path

on:
  push:
    branches:
      - master

jobs:
  mlflow-environment-artifact:
    runs-on: ubuntu-24.04
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
      
      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v3
        with: 
            auto-activate-base: false
            channels: conda-forge,defaults
            environment-file: ml_platform/best_model_artifacts/conda.yaml
            activate-environment: mlflow-env

      - name: Make a Tarball of the Environment and Push it to S3
        working-directory: ml_platform/best_model_artifacts
        env:
            S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
        shell: bash -l {0}
        run: |
            conda-pack -o environment.tar.gz -f
            pip install s3cmd
            source run_spec # Register EXPERIMENT_ID and RUN_ID as env variables