name: Update Artifact Path

on:
  push:
    branches:
      - master

jobs:
  mlflow-environment-artifact:
    runs-on: ubuntu-24.04
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          special-characters-workaround: true

      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v3
        with: 
            auto-activate-base: false
            environment-file: ml_platform/best_model_artifacts/conda.yaml
            activate-environment: mlflow-env

      - name: Make a Tarball of the Environment and Push it to S3
        working-directory: ml_platform/best_model_artifacts
        env:
            S3_ENDPOINT_URL: "${{ secrets.S3_ENDPOINT_URL }}"
        shell: bash -l {0}
        run: |
            conda-pack -o environment.tar.gz -f
            source run_spec # Register EXPERIMENT_ID and RUN_ID as env variables
            aws s3 cp environment.tar.gz \
                s3://customerintelligence/ml_platform/mlartifacts/${EXPERIMENT_ID}/${RUN_ID}/artifacts/iris_xgb/test.tar.gz
                --endpoint-url ${S3_ENDPOINT_URL}