name: Update Artifact Path

on:
  push:
    branches:
      - master
    tags:
      - "[0-9]*.[0-9]*.[0-9]*"

env:
  best_model_directory: ml_platform/best_model_artifacts # metadata and artifactory for the best mlflow run
  mlflow_artifactory_root_path: ml_platform/mlartifacts # mlflow server s3 root path 

jobs:
    deploy-to-kserve:
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        runs-on: ubuntu-24.04
        steps:
            - name: Check Out Code
              uses: actions/checkout@v4

            - name: Set up Kubectl
              uses: azure/setup-kubectl@v4
            
            - name: Set K8s context
              uses: Azure/k8s-set-context@v4
              with:
                kubeconfig: ${{ secrets.KUBECONFIG }}
            
            - name: Load .env file
              uses: xom9ikk/dotenv@v2.3.0
              with:
                  path: ./${{ env.best_model_directory}}
                  mode: best_run
                  load-mode: strict

            - name: Deploy the best mlflow model to Kserve
              working-directory: ${{ env.best_model_directory}}
              env:
                S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                S3_REGION: ${{ secrets.S3_REGION }}
                EXPERIMENT_ID: ${{ env.EXPERIMENT_ID }}
                RUN_ID: ${{ env.RUN_ID }}
              run: |
                envsubst < inference_service/mlflow.yml | kubectl apply -f -
                 
            
            
